services:
  app:
    build: .
    container_name: rails_app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/quotes_journaling_development?encoding=UTF8
      - RAILS_ENV=development
      - WEB_CONCURRENCY=1
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: rails_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: